### ISSUE TITLE
poprawki

### ISSUE THREAD

**Issue by michal-bootcamp** [JoannaKu/Java-Script-9#1]
- [x] nie potrzebujesz instrukcji `break`
- [x] aktualnie masz zadeklarowana funkcje, ale musisz ja jeszcze wywolac

**Comment by JoannaKu** [comment]
zrobione :) wiedziałam, że zapomniałam o czymś istotnym :)

**Comment by michal-bootcamp** [comment]
no i dziala :)
Teraz mozesz jeszcze poprawic wciecie dla calego for od 9 linii, bo widac, ze powinien byc na rowni z var, ktore jest wyzej (bo nie jest wewnatrz niego): https://scr.hu/nwvdn6

Wyrzuc tez `n=10;`, a zamiast tego wywolaj funkcje z takim parametrem: `drawTree(10);`. Mozesz tez wywolac ja kilka razy z roznymi parametrami :)

**Comment by JoannaKu** [comment]
coś namieszałam. Usunęłam n=10, ale chyba nie o to chodziło...

**Comment by michal-bootcamp** [comment]
nie o to. 
Taki zapis:
`var n=drawTree(10);`
jest troche bez sensu w tym przypadku poniewaz oznacza, ze przypisujesz do zmiennej `n` wynik dzialania funkcji drawTree (przekazujac jej jako argument liczbe 10), a funkcja ta nie zwraca wartosci, tylko wyswietla cos w konsoli, wiec i tak sie to wykona.
Dlatego cala linia 1 jest do usuniecia, a na koncu pliku zamien
`drawTree(n);` na `drawTree(10);`
Mozesz tez dorzucic dodatkowe wywolania funkcji np:
`drawTree(5);`
`drawTree(50);`
i zobacz co sie stanie.
Popraw tez to wciecie: https://scr.hu/nwvdn6

**Comment by JoannaKu** [comment]
ok, poprawiłam wszystko, ale nie widzę żadnych różnic w zapisie w konsoli pomiędzy różnymi argumentami jakie wpisałam :(

**Comment by michal-bootcamp** [comment]
aaa no tak, bo petla wykonuje sie zawsze do `10` (linia2), zamiast do `n`, czyli wartosci jaka wprowadzisz

**Comment by JoannaKu** [comment]
Poprawione :) działa
